jobs/scheduling/TimeOffRequests.js

This requires some modifications for running on prod

Add TimeOffRequests cron

---

config.js.default
jobs/scheduling/NotifyMoreShifts.js
jobs/scheduling/RecurShifts.js
lib/stathat.js
package.json

NOTE: **REQUIRES RE-RUN OF `npm install`**

This PR adds Stathat logging wrapper and logging to relevant jobs.

---

jobs/scheduling/TimeOffRequests.js

Fixes moment deprecation warnings as per [this SO post](http://stackoverflow.com/questions/23263380/deprecation-warning-moment-construction-falls-back-to-js-date).

remove moment deprecation warnings

---

www/routes/scheduling/index.js
www/views/scheduling/someShiftsCancelled.jade

Adds proper redirects with query params for new shift scheduling. 
Functionally, this PR provides the appropriate query params for redirects to new shift scheduling. This has only been tested with Andrew and I's credentials, though--admin accounts with separate passwords that WiW. And it hasn't been shown to work if we're logged out of WiW when we attempt the redirects. 
Will this work with a non-admin user? Need to test this, and to walk through the SSO token signin flow.

add proper redirect with query params for new shift scheduling

---

console

Console now runs functions without requiring and running all code in tasks
Test by `node console <file> <function>`

console now runs functions without requiring and running all code in tasks

---

app.js

Adds control flow so that new relic is enabled on production, not otherwise.

newrelic fix

---

jobs/scheduling/TimeOffRequests.js

This PR does two things: 
1. Changes time off job to approve time off requests, even when they don't contain regular shifts. 
2. Adds functionality for taking time off which releases taken makeup shifts back into the makeup shift pool.

change time off job

---

tasks/makeEmails.js

Edits the shift update task so: 
1. change api.update(‘user/‘ —> api.update(‘user’) 
2. make it a batch job for update 
Tested by updating WiW.

edit task so it runs as a batch, and makes the call to update if email has been changed

---

jobs/scheduling/RecurShifts.js

Tested by running recurrence job in test location. Everything checks out.

cleanup comments, whitespace in RecurShifts.js

---

jobs/scheduling/MergeOpenShifts.js
jobs/scheduling/RecurOpenShifts.js
jobs/scheduling/TimeOffRequests.js
lib/ColorizeShift.js
package.json
tasks/color.js
test/colorize.js
test/test.js
www/routes/scheduling/index.js

Revises the ColorizeShift library for testing, changes the method invocation for `ColorizeShift` to be more consistent, revises colorize tests, add more colorize tests. 
Also, adds the `nock` library for mocking out API calls for testing. We'll use this library later/soon. 
`lib/ColorizeShift.js` 
then
`test/colorize`
Tested by `npm test`. 
https://admin.crisistextline.org/jira/browse/INT-2

revise ColorizeShift library for testing, revise colorize tests, add more tests

---

config.js.default

Updates shift coloration and number of shifts that need to be open.

add new counselor shifts and colors

---

config.js

add new color and shift incidence config.
Tested by running the new JSON objects through a JSON linter. 
https://admin.crisistextline.org/jira/browse/INT-153

add new color and shift incidence config

---

www/scheduling/shifts/controllers/retrieveAndRenderShiftsToDelete.js
www/views/scheduling/chooseShiftToCancel.jade

fixes a JSON.parse shift.notes bug in jade view
'debug JSON.parse() call in deleteShifts view'

fixed JSON.parse bug

---

test/index.js
test/mergeOpenShifts.js

main fix is setting the node environment to test in the test/index.js file.

debugged mergeOpenShifts and set node env to test in test/index.js

---

email_templates/composeNotifyMoreShifts.js
package.json

add request-promise dependency and fix quotes in emails

---

canvas.js
config.js
email_templates/canvas_dup_emails.txt
email_templates/canvas_dup_names.txt
email_templates/canvas_email_and_name_not_found.txt
email_templates/canvas_email_not_found.txt
jobs/scheduling/AttendanceSync.js
keys.js.default
package.json

automates canvas grading for attending GTW observation

Gtw integration

---

package.json

add request, fixes: 
```
module.js:340
throw err;
^
Error: Cannot find module 'request'
at Function.Module._resolveFilename (module.js:338:15)
at Function.Module._load (module.js:280:25)
at Function.cls_wrapMethod [as _load] (/var/www/elmer/node_modules/newrelic/lib/shimmer.js:235:38)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object.<anonymous> (/var/www/elmer/jobs/scheduling/AttendanceSync.js:4:15)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
at Function.cls_wrapMethod [as _load] (/var/www/elmer/node_modules/newrelic/lib/shimmer.js:235:38)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at …
```

add request to package.json

---

config.js
jobs/scheduling/AttendanceSync.js

fixes bug and naming conventions in the original GTW integration feature
jobs/scheduling/AttendanceSync.js
the usual, don't forget to comment out the mandrill call so that heather doesn't get overloaded w duplicate emails
INT-192

GTWint bug and variable names fixed

---

jobs/scheduling/NotifyMoreShifts.js

uncommented requires, cron and invocation

---

www/scheduling/shifts/controllers/retrieveAndRenderShiftsToDelete.js

https://admin.crisistextline.org/jira/secure/RapidBoard.jspa?rapidView=5&view=detail&selectedIssue=INT-184

Modify retrieve and render shifts to delete and update email to support@

---

jobs/scheduling/AttendanceSync.js

fix a variable name
jobs/scheduling/AttendanceSync.js

variable naming bug fixed

---

jobs/scheduling/RecurShifts.js

Improve error handing for batch post failing in order to assist in debugging " Sorry! WhenIWork is loading story.."
https://admin.crisistextline.org/jira/secure/RapidBoard.jspa?rapidView=5&view=detail&selectedIssue=INT-199
https://admin.crisistextline.org/jira/secure/RapidBoard.jspa?rapidView=5&view=detail&selectedIssue=INT-204

Improve error handing for batch post failing

---

tasks/usersWithTimezones.js

Creates a CSV of users and their self reported timezones
Run module.exports.usersTimezones();
https://admin.crisistextline.org/jira/secure/RapidBoard.jspa?rapidView=5&view=detail&selectedIssue=INT-179
Same Q as last time about using config.WhenIWork

Create user dump to CSV

---

tasks/timeOffRequests.js

Creates comprehensive time off requests task that dumps data to exported CSV
The flow of the file is written out at the top of the module export, functions are written below in order of execution. 
execute module.exports.timeOffRequests() with or without designating params 
https://admin.crisistextline.org/jira/secure/RapidBoard.jspa?rapidView=5&view=detail&selectedIssue=INT-181
Why don't we use config.WhenIWork in tasks?

create comprehensive time off requests dump

---

config.js

Updates open shift numbers and coloration.

update open shift numbers and coloration

---

jobs/scheduling/AttendanceSync.js
test/GTWsampleData.js
test/attendanceSync.js
test/helpers/base.js
test/index.js

tests jobs/scheduling/AttendanceSync.js and adds sample data
npm test
https://admin.crisistextline.org/jira/browse/INT-168

initial testing

---

jobs/scheduling/MergeOpenShifts.js
jobs/scheduling/RecurShifts.js
jobs/scheduling/TimeOffRequests.js
jobs/scheduling/updateCanvas.js
tasks/color.js
tasks/deleteOpenUnpubShifts.js
www/scheduling/index.js

Disk space on Elmer is filling up rapidly from logs, so this PR reduces less useful logging and makes it more concise. Along with solving some minor bugs)
https://admin.crisistextline.org/jira/secure/RapidBoard.jspa?rapidView=5&view=detail&selectedIssue=INT-165&quickFilter=10

Made logs more concise

---

jobs/training/pollCanvasForGraduatedUsersThenCreatePlatformAccount.js

Changed the title of the graduation assignment from 'Graduation' to 'Platform Ready!' to reflect the Canvas change 
graduation cronjob script
run the file in node
https://admin.crisistextline.org/jira/browse/INT-249

changed assignment name from 'Graduation' to 'Platform Ready'

---

config.js
jobs/scheduling/AttendanceSync.js
jobs/training/pollCanvasForGraduatedUsersThenCreatePlatformAccount.js

adds canvas assignment name string to config and calls attendance and graduation functions upon the start of the app
config, attendancesync, and pollCanvasForGrads
run in node
https://admin.crisistextline.org/jira/browse/INT-251

added canvas assignment name strings to config

---

config.js
jobs/scheduling/NotifyMoreShifts.js
tasks/shiftsDump.js
test/helpers/checkHTTPResponses.js

Creates a CSV of all the shifts within the designated 50 day range
run: node console shiftsDump go
https://admin.crisistextline.org/jira/secure/RapidBoard.jspa?rapidView=5&view=detail&selectedIssue=INT-180

create all shift dump

---

jobs/scheduling/NotifyMoreShifts.js

Adds in necessary params for this job to run. https://github.com/ncb000gt/node-cron#api

fix NotifyMoreShifts job

---

www/scheduling/shifts/controllers/retrieveAndRenderShiftsToDelete.js

For some reasons, including the `include_objects=false` query broke functionality. 
This fixes it.

hotfix for include_shifts breaking functionality

---

config.js
jobs/training/pollCanvasForGraduatedUsersThenCreatePlatformAccount.js

revises the graduation script to check both 'Platform Ready!' and the score for 'Final Exam' assignment before creating a platform account
jobs/training/pollCanvasForGraduatedUsersThenCreatePlatformAccount.js
run in node, check against our records in canvas
i've found dante's inferno in the heart of the canvas api
https://admin.crisistextline.org/jira/browse/INT-235

added check for two assignments before platform creation functionality

---

jobs/scheduling/AttendanceSync.js

adds catch blocks to the attendancesync script
jobs/scheduling/AttendanceSync.js
run attendanceSync (change the mandrill email address please so that heather doesn't get bombarded by our testing) and attendanceSync tests
INT-305

added catchblocks to attendancesync script

---

tasks/timeOffRequests.js
www/app.js
www/data/index.js
www/scheduling/index.js

Exposes a route that responds with a CSV of TimeOffRequests from WiW
node www/app.js
navigate to localhost:3000/data/wiw/timeoff?token={{KEYS.dataRoute}}
expect CSV string
https://admin.crisistextline.org/jira/secure/RapidBoard.jspa?rapidView=5&view=detail&selectedIssue=INT-301

Create route for Time Off Requests

---

.travis.yml
README.md
keys.js.default
package.json
test/dropMeltedUsers.js
test/helpers/base.js
test/helpers/checkHTTPResponses.js
test/index.js
test/updateCanvas.js

Standardizes Elmer to V 1.0.0
Adds Istanbul test coverage and foundations for Travis/Coverall
npm run-script test-travis
The .travis file is not being used yet.
Adding Travis to a repo requires admin permission for the repo. 
https://admin.crisistextline.org/jira/secure/RapidBoard.jspa?rapidView=5&view=detail&selectedIssue=INT-264
https://admin.crisistextline.org/jira/secure/RapidBoard.jspa?rapidView=5&view=detail&selectedIssue=INT-219

Auto testing

---

api_wiw/WiWRequests.js
keys.js.default
tasks/timeOffRequests.js
www/data/index.js

Creates routes for the Baby CRM
https://admin.crisistextline.org/jira/secure/RapidBoard.jspa?rapidView=5&view=detail&selectedIssue=INT-313

add routes for MIA 2 weeks and filtered

---

email_templates/compose2WeekMissedEmail.js
keys.js.default
package.json
www/data/googleSheets.js
www/data/helpers.js
www/data/index.js

Make the data routes more descriptive 
Modularize the helper functions
Enable google sheets integration
www/data/index.js and follow the functions calls out of there
You should be able to hit all of the included routes when running www/app.js
Be careful with /email/MIA2WeeksWithoutTimeoff because it actually sends emails. I disabled the mass emailing functionality until we decide to move forward with that. To send individual emails include a body with the post like
{
"users": [
{"first_name": "A", "last_name": "P", "email": "email@gmail.com"},
{"first_name": "A", "last_name": "P", "email": "email@gmail.com"}
]
}
You can update the sheet No Contact List in https://docs.google.com/spreadsheets/d/1j49XjT1xcoN8Q5bn-EFA5vBGCgXjgUc3j8CcDQfzTW8/edit#gid=1722145441
and those email addresses …

Intergrate google sheet api and build 2 week email functionality

---

www/canvas/helpers.js

Change Sherlock sorting to be based on the questions title string instead of id #.
https://admin.crisistextline.org/jira/secure/RapidBoard.jspa?rapidView=5&view=detail&selectedIssue=INT-365

Modify sort to use question numbers

---

www/canvas/helpers.js

Parses Typeform answers for multiple choice and select box type questions as well adds a fallback for other questions that result an the answer being an object.
https://www.typeform.com/help/webhooks/#identifying_questions
https://admin.crisistextline.org/jira/secure/RapidBoard.jspa?rapidView=5&view=detail&selectedIssue=INT-384

Interpret other sherlock answer types

---

www/data/helpers.js

Unified letter casing between email addresses stored in different locations
https://admin.crisistextline.org/jira/secure/RapidBoard.jspa?rapidView=5&view=detail&selectedIssue=INT-382

Filter email addresses regardless of case

---

config.js
jobs/training/pollCanvasForGraduatedUsersThenCreatePlatformAccount.js

final used to be out of 100, now it's out of 70, the minimum passing grade needed to be updated
DO NOT MERGE BEFORE SEPTEMBER 22 
jobs/training/pollCanvasForGraduatedUsersThenCreatePlatformAccount.js
add keys and config, you know the drill

minimum final score changed to 60

---

www/app.js
www/scheduling/index.js

add more informative logging for debugging on prod

---

www/scheduling/index.js

add logging

---

cache.js
www/app.js
www/scheduling/index.js

remove promises from allUsers function, add error handling

---

email_templates/firstMeltInvoluntary.js
email_templates/firstMeltVoluntary.js
email_templates/secondMeltInvoluntary.js
email_templates/secondMeltVoluntary.js

Adds survey link to training melt emails. 
https://admin.crisistextline.org/jira/browse/INT-426

add survey link to training melt emails

---

www/canvas/index.js

Forces assignments to be submitted after they are graded so that Canvas alerts trainers that there is a new submission that has not been graded yet.
https://admin.crisistextline.org/jira/secure/RapidBoard.jspa?rapidView=5&view=detail&selectedIssue=INT-407

assign grades before submitting assignment

---

config.js
www/app.js
www/jenkins/index.js
www/jenkins/removeChurned.js

automates churn users job and incorporates the WiW queue
www/jenkins
run www/app.js locally 
curl a string to the route from your terminal in the format 'NUMBERS EMAIL NUMBERS EMAIL' numbers can be arbitrary, they stand in for the date stamp that the actual emails will have. email has to be an email of a churned user (check JIRA ticket for sample curl command)
before curling, wait for the WiW cache to fill
https://admin.crisistextline.org/jira/browse/INT-320

jenkins route built

---

ctlOnline.js
jobs/scheduling/dropMeltedUsers.js
www/canvas/helpers.js
www/canvas/index.js

Adds the CC1 Role for Trainees who complete assignment 'Full Roleplay' in Typeform.
This Role on CTL online allows them to start scheduling shifts.
Add a user to a Canvas course (I used myself)
Input passing grades for assignment 1-8
View user CTL Online Roles on https://online.crisistextline.org/user/${userID}/edit
Make sure Role "Crisis Counselor 1" is not selected
Node www/app.js
Post to localhost:3000/canvas/typeformAssignment/Full Roleplay 
Use the following body with the email for Canvas account being used: 
{
"event_id": "UwVP9f9sGU",
"event_type": "form_response",
"form_response": {
"form_id": "L5aBhG",
"token": "875527530cbc8ec306774088db80887f",
"submitted_at": "2016-08-12T14:49:14Z",
"calculated": {
"score": 2
},
"definition": {
"id": "L5aBhG",
"title": "",
"fields": [
{
"id": …

Add role to trainees who complete Full Roleplay

---

www/canvas/index.js

Use CONFIG.root_dir  instead of relative path navigation
https://admin.crisistextline.org/jira/secure/RapidBoard.jspa?rapidView=5&view=detail&selectedIssue=INT-444

Route was unable to find canvas.js

---

www/canvas/index.js

Reduce emails sent to heather in two ways:
1: Create a small cache of users that emails have been sent to preventing multiple emails about the same user.
2: Only call errFunc  once in retrieveUserCourseAssignmentIds.
https://admin.crisistextline.org/jira/secure/RapidBoard.jspa?rapidView=5&view=detail&selectedIssue=INT-431

Create mini cache of Typeform users with errors and reduce calls to email

---

canvas.js

fixes the reference error in canvas console logs

fixed broken logs

---

canvas.js
www/canvas/index.js

added optional delay parameter

---

jobs/training/meltedDataDumpToSlack.js
jobs/training/pollCanvasForGraduatedUsersThenCreatePlatformAccount.js
keys.js.default

Stops Cron jobs from running on start up to limit calls to Canvas

Stop Crons from running on start

---

canvas.js
www/canvas/index.js

Remove undefined Params

---

canvas.js
jobs/training/meltedDataDumpToSlack.js
jobs/training/pollCanvasForGraduatedUsersThenCreatePlatformAccount.js
test/meltedDataDumpToSlack.js

Method fixed on Canvas
