jobs/scheduling/RecurShifts.js, package.json
When a user creates a new individual shift on WhenIWork, this job will run and recur that shift for a specified number of years (currently 5). This job will also publish shifts a month from the date of the job running. (The user can't see her shifts after then.) 
`RecurShifts.js` 
@TODO: moving config variables into the config.js file. For now, for this to work, add the requisite developer keys to `base.js`. 
We dealt with a lot of API limitations in getting this to work. More documentation of what limitations to follow. 
1. How can this be refactored, generally? 
2. Note the two `firstTask` and `task` functions. These are slightly different functions--`firstTask` runs as the first function task that `async.waterfall` runs, and `task` runs as the last 27 tasks run by waterfall. …
=> Add functionality which recurs new shifts and publishes them

config.js.default, jobs/scheduling/NotifyFirstShift.js, jobs/scheduling/RecurShifts.js, jobs/scheduling/TimeOffRequests.js, www/routes/scheduling/index.js
Adds a cron job to RecurShifts, extract time and location constants to config.js. (Note that we've committed `time_interval` and `locationID` constants to the `config.js.default` config template file, since it's not insecure to publish these. 
Has not yet been tested. 
Since all cron jobs run first on start, start the app to test if shift recurrence, first shift notification, and time off request auto-approval works. 
Is assigning `const CONSTANT_NAME = global.config.locationID.variable_name` at the top of files superfluous? Should we just use references to `global.config` everywhere, instead of defining constant names? 
@andrewjgremmo--did I make the required changes in `TimeOffRequests.js` for prod?
=> add cron job to RecurShifts, extract time and location constants to config.js

app.js, jobs/scheduling/NotifyFirstShift.js, jobs/scheduling/RecurShifts.js, www/routes/scheduling/index.js
Removes defined constants from all files, uses `global.config.XXXX.YYYY` variables instead. Also adds control flow in `config.js` which assigns a test location ID.
=> remove `const`, add test environment changes to config.js

config.js.default, www/routes/scheduling/index.js
Add batch shift deletions to the delete all shifts functionality. Note that it creates an open shift in the place of the upcoming shift (as per our philosophy of only opening up shifts one week from the present), and deletes the rest. 
Manually tested by creating two recurring shifts, extracting the function (starting on line 48), and running it using the Node REPL. Confirmed that shifts were deleted. 
Note that this breaks on high volumes of shifts. (For instance, if a user recurred 24 shifts over five years.) Works with normal volumes: one user's two shifts, recurred over five years.
=> add batch deletions to delete all shifts request

jobs/scheduling/MergeOpenShifts.js, www/routes/scheduling/index.js
When we create openshifts for a time period for which open shifts already exist, those open shifts aren't always automatically incremented by one. Instead, multiple open shifts will then exist in that time slot. 
This is functionally harmless, but potentially confusing for the user. 
This PR finds time slots for which there are multiple open shifts, and merges those shifts into one shift. (While incrementing the quantity on that one shift, so that it can represent multiple shifts.)
=> Merge openshifts

www/routes/scheduling/index.js, www/views/scheduling/cancelShift.jade
Currently, when a user goes to autologin to WhenIWork, we detect if it's an invalid username (their account wasn't created by us) and we redirect them to the login page accordingly.
However, this logic is not applying to the cancel shifts route. So, this PR adds the relevant `failureCallback` method to `api2`'s authentication call.
Attempt to cancel all shifts as a user with a manually created WiW account.
=> Autologin for shift cancellation

jobs/scheduling/TimeOffRequests.js
If a user creates a timeoff request, but she has not scheduled any shifts during that timeoff range, this no longer crashes the app. 
(previously would break at `response.shifts.forEach(function(shift) {`. 
Manually tested by creating a timeoff request not containing any shifts within its scope, and running. 
Closes #26.
=> fix crash caused by timeoff requests not including shifts within their range

jobs/scheduling/TimeOffRequests.js, package.json, www/public/javascripts/main.js, www/routes/scheduling/index.js, www/views/layout.jade, www/views/scheduling/allShiftsCancelled.jade, www/views/scheduling/chooseShiftToCancel.jade, www/views/scheduling/someShiftsCancelled.jade
1. adds the individual deletion of shifts functionality to Elmer. 
2. Also removes the bulk deletion route of shifts. 
1. When the user navigates to online.crisistextline.org/schedules, she'll see a new button to the page which says "drop individual shifts" (to be added.) 
2. Clicking this button will GET the `/scheduling` route on Elmer, displaying a page which lists all the user's shifts in a checkbox form. Only two checkboxes are able to be checked at one time, roughly reflecting WhenIWork's API limit. 
3. When the user checks a shift's box and submits the form, we POST to the `/delete-shifts` route. 
4. The user is redirected to a new view: `someShiftsCancelled.jade`, which then gives a link for the user to be redirected back to When I Work, so that they can schedule another shift. …
=> add individual deletion of shifts

config.js.default, jobs/scheduling/MergeOpenShifts.js
Previously, our `MergeOpenShifts` job exponentially increased the `instances` number on an openshifts. 
(If two openshifts had the same `instances` number, they'd both get updated with the new instances number and neither would be deleted. So if we begin with two open shifts, each with an instance number of 1, they'd both be updated to 2, then 4, then 8, then 16--each time the cron job runs once an hour.)
This fixes this problem with a flag. Also adds some camelCase, fixes whitespaces, and moves the cronjob string out into the global config.
=> Openshifts

jobs/scheduling/TimeOffRequests.js
We were sending a moment date object instead of the proper date string when querying for shifts that should be changed given a time off request. 
This fixes that issue.
=> fix date format for finding shifts that fell within timeoff requests, was preventing them from being found

.gitignore, config.js.default, jobs/scheduling/RecurOpenShifts.js, tasks/recur.js
Adds open shift recurrence based on a new model: 
1. Create a config file listing the number of shifts available for specific times (perhaps listed as a multiple of the number of `counselors_per_supervisor`)
2. revise recurrence job so that it runs every so often
3. master scheduling doc + WiW Shift Sums tab (link here: https://docs.google.com/spreadsheets/d/120A2OqHk5XG62-b4Xai0LeWiEBzpQbgmLpQRXvoP5XQ/edit#gid=685762792) 
4. What does function do? 
5. check config file
6. runs every two hours, pulls all shifts which start between 2 and 2:01 (start and end params are referring to the start and end times for the START TIME of the shift, not the whole shift itself.) 
7. finds all shifts for that time period for the regular shifts location (NOT including makeup shifts, which we want to save …
=> add revised open shift recurrence

config.js.default, jobs/scheduling/MergeOpenShifts.js, jobs/scheduling/RecurOpenShifts.js, lib/ColorizeShift.js, test/test.js
This PR should import a new library called ColorizeShift for use anywhere in the codebase. For now, it is required to explicitly call it. In the future, it may be possible to modify the wheniwork_nodejs library to support middleware, but this will do for now.
If a shift is defined in the config file, it will add a `color` property to the shift and return the new shift. Otherwise, it will just return the shift passed to it.
=> Colorize recurred and merged shifts

jobs/scheduling/RecurOpenShifts.js, www/routes/scheduling/index.js
Refactors open shift recurrence: 
1. We check to see if open shifts have already been recurred for the next week
2. Check if the number of open shifts matches up to the correct number of open shifts
3. If the numbers don't match, we delete the open shifts and add the correct number again
Tested by running job on test WhenIWork environment. 
Closes [JIRA INT-10](https://admin.crisistextline.org/jira/browse/INT-10). 
1. Think through all delete shift / open shift creation cases. Think about if this works with edge cases.
=> refactor open shift recurrence so that incorrect number of open shits are deleted

config.js.default
Darkens the gray color of non-red shifts in the `regular_shifts` location. Need to add this to the `config.js` file after this is deployed.
=> darken gray color of open shifts

app.js
Otherwise, new relic doesn't report.
=> move require() statement closer to top of first module loaded in

jobs/scheduling/RecurOpenShifts.js
Previously, open shift recurrence only checked to see if the `correctNumberOfOpenShiftsToAdd` param was greater than zero. In that case, we'd add shifts. In other cases, we'd do nothing. 
This PR changes that logic so that we check to see if the `correctNumberOfOpenShiftsToAdd` param is negative. (That means that the number of shifts open is greater than what we actually want.) 
In that case, we delete shifts. 
Creating open shift times that are 1) greater than the expected amount, 2) less than the expected amount, and 3) just right in the test WiW environment. Running it.
=> change open shifts to modify open shift count if there are too many open shifts

config.js.default, www/routes/scheduling/index.js
Adds an endpoint to retrieve shifts and their owners' emails for a specific time range. 
Will be used on the CTL platform to send notification emails to users who are missing their shift. 
Run locally. Use Postman to hit this route to find shifts between 2 and 4pm EST on Tuesday, March 22nd. 
`localhost:3000/scheduling/shifts/time-interval?start=1458669600&end= 1458676800`
=> add endpoint to retrieve shifts and their owners' emails for a time range 

www/routes/scheduling/index.js, www/views/scheduling/chooseShiftToCancel.jade, www/views/scheduling/someShiftsCancelled.jade
Adds makeup shift deletion functionality. 
Core logic happens in `www/routes/scheduling/index.js`. 
Running `node app.js` on your local box without passing any `NODE_ENV` env variables will make this run in the test environment, and the default `regular_shifts` location the test location. 
Within WhenIWork, pick up some shifts from both the makeup shifts and test locations. Then, navigate to 
`http://localhost:3000/scheduling/shifts?email=<email>&token=<token>` and then delete some shifts, homie!
Currently, API calls take a long time--considering decreasing search field for first API call from 365 days? 
Also--add a spinning wheel between when call is made and when it happens.
=> Add makeup shift deletion functionality

app.js, config.js.default, jobs/scheduling/MergeOpenShifts.js, jobs/scheduling/TimeOffRequests.js, lib/ColorizeShift.js, www/routes/scheduling/index.js
Makeup shifts created by timeoff requests were not deliberately being colorized. This colorizes them to be light gray if they're non-urgent, and red if they are during urgent times. 
This also changes how `colorizeShift` works to support makeup shifts being colorized a different way. 
Tested by confirming that makeup shifts.
=> colorize makeup shifts created by timeoff requests, refactor `colorizeShift` accordingly

tasks/deleteOpenUnpubShifts.js
Adds a task to delete all unpublished open shifts. (This was likely causing the problem where we'd see a lot of unpublished open shifts.)
=> add task to delete all unpublished open shifts

jobs/scheduling/MergeOpenShifts.js, tasks/merge.js
Previously, makeup shifts weren't getting merged. (There were many makeup shifts appearing for same time as opposed to one makeup shift with many instances.)
This PR updates the job so that they are merged together, and colorizes them properly. 
This also adds a task so we can run the merge ourselves. 
Tested in the `test` and `test2` environments, then tested again by running against production via the task. Works.
=> add merge makeup shift functionality, refactor, merge task

jobs/scheduling/RecurOpenShifts.js
Turning off open shift recurrence specifically so that we can open two weeks' worth of open shifts for C12.
=> turn off open shift recurrence

www/routes/scheduling/index.js
Adds user information to the response of the API endpoint `scheduling/shifts/time-interval`. Thus, the API call sends the `notes` param attached on the user object. This will allow us to send late to shift notification messages just to those users who have confirmed their time zone. 
Tested by using Postman to hit the endpoint and return the requisite data. 
https://admin.crisistextline.org/jira/browse/INT-57
=> add user data to scheduling/shifts/time-interval call response

www/routes/scheduling/index.js, www/views/scheduling/chooseShiftToCancel.jade
Previously, when a user had only booked one-time (makeup) shifts, and not regular (weekly) shifts, their shift deletion screen didn't load because Jade would error out. 
This fixes that. 
(We also add a small `return` statement in `/www/routes/scheduling/index.js` to avoid the potential "can't set headers after they are sent" error. 
Tested by booking shifts in prod on WhenIWork, and then deleting them by running Elmer locally. 
Closes https://admin.crisistextline.org/jira/browse/INT-72
=> fix delete shift, not loading if no weekly shifts to delete

jobs/scheduling/RecurOpenShifts.js
Turns on open shift recurrence. 
Tested by running on the test environment. 
Because we previously wanted the new cohort 12 graduates to be able to schedule for any time within a two week (as opposed to one week) scheduling window on WiW, we needed to turn off open shift recurrence (which operates on the one week scheduling window assumption) for this to work. 
We no longer need to have graduates be able to schedule out shifts two weeks in advance.
=> turn on open shift recurrence

config.js.default, jobs/scheduling/MergeOpenShifts.js, jobs/scheduling/NotifyFirstShift.js, jobs/scheduling/NotifyMoreShifts.js, jobs/scheduling/RecurOpenShifts.js, jobs/scheduling/RecurShifts.js, tasks/schedule.js, test/loginusercreation.js, www/scheduling/shifts/controllers/deleteShiftsAndRedirect.js
Previously, our model of taking open shifts only allowed users to take weekly shifts from the next week. 
Now, we want to open up our shift model to allow users to take weekly shifts from *the next two weeks.*
This PR modifies the Elmer codebase so that it supports that change. 
WhenIWork returns shift `start_time` and `end_time` parameters in the following format: "Wed, 01 Jun 2016, 12:00:00 -500". 
However, the timezone doesn't match the format that `moment()` expects when it parses time strings: "-0500". Moment, when it can't properly parse that time string, defaults to creating a date based on the current date. Which is not good. It also fails silently. 
So the following global function added to `config.default.js`, ``MAKE_WIW_TIME_STRING_MOMENT_PARSEABLE`
`, accepts a string returned …
=> add support a two-week open shift window

jobs/scheduling/RecurShifts.js
Adds better error handling, debug logging to RecurShifts.js. 
Tested on local as working. 
Strangely enough, it seems like while the `decrementPrevWeeksAndNextWeeksOpenShiftsByOne` function is working locally on test, it doesn't seem to be working on production. 
https://admin.crisistextline.org/jira/browse/INT-136
=> add better error handling, debug logging to RecurShifts.js

jobs/scheduling/RecurShifts.js
`decrementPrevWeeksAndNextWeeksOpenShiftsByOne` wasn't working, because nothing ever got past this `      if (shift.is_open && (convertedShiftStartTime === prevWeekShiftStartTime || convertedShiftStartTime === nextWeekShiftStartTime)) {`
This was because shifts were being returned by the WiW API in the UTC-0700 timezone. However, when we run moment() on the shifts, we change it to the -0400 time zone since we specify the default timezone as -0400 in `config.js`. So string equality fails. 
This converts every shift's open time in order to check it. 
Manually tested on local, works. But will it work in prod???? ❓ ❓ 
https://admin.crisistextline.org/jira/browse/INT-136
=> add fix for incompatible server/WiW time zone issue

jobs/scheduling/RecurShifts.js
Some of the error handling added a few PRs ago broke weekly shift recurrence. 
Strangely enough, we witnessed that the shifts were recurring when we ran on local with test location. But weren't recurring when we ran on local, with prod location. 
After we took out the error handling, things work again. This deserves more attention in the future. 
Manually tested on local with prod and test locations.
=> fix weekly shift recurrence

config.js, email_templates/composeNotifyBookedShift.js, jobs/scheduling/RecurShifts.js, jobs/scheduling/helpers/notifyUserBookedShift.js
Emails any users that booked a shift after they have received their second_shift_notification (or are too old to)
1) Change the runJobs file to only run this
2) Book a new shift on whenIwork with an account that has already received second_shift_notification or more than the designated age
3) node runJobs 
4) make sure you get an email about your newly booked shift
https://admin.crisistextline.org/jira/secure/RapidBoard.jspa?rapidView=5&view=detail&selectedIssue=INT-164
=> Notify users via email anyime they book a new recurring shift

jobs/scheduling/RecurShifts.js
Previously, we removed relevant objects from being returned in the response for a `/get` request to WhenIWork. 
This broke things in this job, which caused our app to restart a bajillion times, which caused us to hit rate limits in Canvas and GTW.
=> hotfix for not returning objects in response

jobs/scheduling/dropMeltedUsers.js, jobs/scheduling/helpers/updateCanvas.js, test/dropMeltedUsers.js, test/index.js
It checks for users who have been marked by trainers in Canvas as "deactivated," finds them in WiW, and deletes them and their shifts.
jobs/scheduling/dropMeltedUsers
npm test, and/or:
1. Create a fake Canvas user.
2. Enroll the user in a course.
3. Select "deactivate user" for your user in the list of students in the course.
4. Create a user with the same email address in WiW.
5. Sign that user up for a shift or two in WiW.
6. Run dropMeltedUsers with node (including the appropriate CONFIG and KEYS variables as needed to help it run). Alternatively, use runJobs, but only set it to run dropMeltedUsers.
7. Make sure the user's WiW account no longer exists and their shifts no longer belong to them.
[INT-130](https://admin.crisistextline.org/jira/secure/RapidBoard.jspa?rapidView=5&view=detail …
=> Drop melted users

config.js, jobs/scheduling/AttendanceSync.js, jobs/scheduling/helpers/updateCanvas.js, jobs/training/pollCanvasForGraduatedUsersThenCreatePlatformAccount.js, www/app.js, www/canvas/index.js
**What's this PR do?**
Create a route for the platform to update canvas when a user attends their shift
**How should this be manually tested?**
Already tested with TC, but we can test again ->
Can test by using a real canvas email to Postman put to /canvas/firstShift with a body that contains {"user": {"name":"Whoever you want","email":"realCanvasAccount@crisistextline.org"}} and see if the user with that email address had their assignment updated.
**Any background context you want to provide?**
This is a remake of PR https://github.com/CrisisTextLine/Elmer/pull/161
**What are the relevant tickets?**
https://admin.crisistextline.org/jira/secure/RapidBoard.jspa?rapidView=5&view=detail&selectedIssue=INT-236
=> Update Canvas when CCs attend first shift

www/scheduling/shifts/controllers/deleteShiftsAndRedirect.js
Fixes shift deletion. Adding the `include_objects=false` call to the get request here broke shift deletion. 
Manually tested by running the functionality in the weekly shifts environment on my local. 
Closes https://admin.crisistextline.org/jira/browse/INT-270
=> fix shift deletion

jobs/scheduling/RecurShifts.js
Once again, the `include_objects=false` flag was breaking jobs. 
This fixes the recurrence job. 
https://admin.crisistextline.org/jira/browse/INT-275
=> fix recur shifts by removing "include_objects=false" flag

config.js
Allows us to more easily debug timing messiness on prod by making our CONSOLE_WITH_TIME call log in EST. 
Tested locally by running `node runJobs.js`.
=> make CONSOLE_WITH_TIME abide by timezones in logs

jobs/scheduling/MergeOpenShifts.js
Remove include_objects flag for merge open shifts. Was breaking merge open shifts. 
Tested by running merge task, which worked.
=> remove include_objects flag for merge open shfits

jobs/scheduling/helpers/notifyUserBookedShift.js, jobs/scheduling/helpers/updateCanvas.js, test/helpers/checkHTTPResponses.js, www/canvas/helpers.js, www/canvas/index.js
Creates a route for assignments submitted by typeform.
Add Canvas functionality for submitting assignments.
1: Create a test Canvas account with a Canvas assignment that accepts text based submission
2: node www/app.js 
3: post to localhost/canvas/typeformAssignment/:assignment
with a typeform like body (swap in the email associated with the canvas account):  `{
"event_id": "UwVP9f9sGU",
"event_type": "form_response",
"form_response": {
"form_id": "L5aBhG",
"token": "875527530cbc8ec306774088db80887f",
"submitted_at": "2016-08-12T14:49:14Z",
"calculated": {
"score": 15
},
"definition": {
"id": "L5aBhG",
"title": "",
"fields": [
{
"id": "3",
"title": "Question text: 3",
"type": "textfield"
},
{
"id": "2",
"title": "Question Bool: 2>",
"type": "yes-no"
},
{
"id": "1",
"title": "Please enter …
=> Create route for typeform submissions and post to Canvas submissions

package.json
We removed the '/2's from elmer without updating the wiw version yet.
=> Updated WiW unofficial

jobs/scheduling/RecurShifts.js, jobs/scheduling/helpers/notifyUserBookedShift.js
We were notifying CC's that their shifts have been scheduled before they were successfully recurred. So if recurring failed they would get notified every time we tried to recur their shifts. This has been modified so we only notify them (and 
1. Add this to the top of the file:
global.KEYS = require('../../keys.js');
global.CONFIG = require('../../config.js');
CONFIG.locationID.regular_shifts = CONFIG.locationID.test;
console.log('testing');
2. Create a test shift in wheniwork
3. node RecurShifts.js and you should get an email. 
https://admin.crisistextline.org/jira/secure/RapidBoard.jspa?rapidView=5&view=detail&selectedIssue=INT-362
There's separate small formatting bug that is logging errors, but I don't believe is causing other issues. I added it to the backlog.
=> Notify CCs and delete open shifts after WiW confirms recurring shifts

jobs/scheduling/RecurShifts.js
Fixes RecurShifts to accurately create future shift chains (currently for 5 years in the future). Previously future chains had started at a weird date.
RecurShifts.js.
Since recurNewlyCreatedShifts is such a big, complex function, I find it easiest and safest to do the following:
1. Add GLOBAL.KEYS and GLOBAL.CONFIG to the top of the recurShifts.js file:
a) GLOBAL.KEYS = require('../../keys.js');
b) GLOBAL.CONFIG = require('../../config.js');
2. Add GLOBAL.KEYS to the top of the WiWCCApi.js file: GLOBAL.KEYS = require('../keys.js');
3. Comment out the CronJob on line 11 of the recurShifts.js file.
4. Comment out lines 26-55 of recurShifts.js.
5. Comment out all lines from 114-232 inclusive (the end of the recurNewlyCreatedShifts function).
6. Add the following sample shift array right …
=> Fixed bug causing future shift chains to start at odd times.

test/recurOpenShifts.js
fixes 9 to 19 in a unit test. the expected number has changed because we have updated our config file
test/recurOpenShifts.js
npm test
=> fixed the test

jobs/scheduling/RecurShifts.js, www/scheduling/shifts/controllers/retrieveAndRenderShiftsToDelete.js
Runs the recurrence script for CC's who's shifts have not recurred by the time they try to delete recurring shifts.
Check the modularization in jobs/scheduling/RecurShifts.js starting on line 57
Run Elmer locally.
Create a recurring shift in the test location.
Hit the route to delete a recurring shift '/scheduling/shifts?email=*******&token=******' before the recurShifts script runs.
You should received the error 'Sorry! There is an error loading your shifts. Please refresh the page in 1 minute. If this problem persists please let us know via email to support@crisistextline.org' and your terminal should show the logs for recurring a shift. 
Refreshing the page should now show that shift available to delete.
https://admin.crisistextline.org/jira/secure/RapidBoard.jspa?rapidView=5&view=detai …
=> Recur shifts that are not recurred when CC tries to delete recurring shifts

www/canvas/helpers.js
Typeform error in Webhooks is causing formResponse.definition = null 
This section should contain the questions from the form. We have a ticket in process with them.
https://admin.crisistextline.org/jira/secure/RapidBoard.jspa?rapidView=5&view=detail&selectedIssue=INT-458
=> Temporary typeform workaround
